(()=>{
'use strict';
const CONFIG_URL='admin-runtime-config.json';
const SESSION_KEY='bantai-university-photo-admin-code';
const $=s=>document.querySelector(s);
const els={backend:$('#backend-status'),login:$('#admin-login'),form:$('#admin-login-form'),code:$('#admin-code'),remember:$('#remember-session'),unlock:$('#unlock-admin'),loginStatus:$('#login-status'),dashboard:$('#admin-dashboard'),refresh:$('#refresh-queue'),lock:$('#lock-admin'),queue:$('#review-queue'),empty:$('#review-empty'),queueStatus:$('#queue-status'),filters:[...document.querySelectorAll('.filter')],counts:{pending:$('#count-pending'),approved:$('#count-approved'),rejected:$('#count-rejected'),published:$('#count-published')},dialog:$('#review-dialog'),dialogStatus:$('#dialog-status-badge'),dialogUniversity:$('#dialog-university'),dialogMeta:$('#dialog-meta'),dialogGallery:$('#dialog-gallery'),dialogId:$('#dialog-id'),dialogCount:$('#dialog-count'),dialogDate:$('#dialog-date'),dialogUniversityId:$('#dialog-university-id'),dialogAgreements:$('#dialog-agreements'),reviewerNote:$('#reviewer-note'),download:$('#download-package'),markPending:$('#mark-pending'),reject:$('#reject-submission'),approve:$('#approve-submission'),publish:$('#publish-submission'),dialogActionStatus:$('#dialog-action-status')};
let config=null,adminCode='',submissions=[],activeFilter='pending',activeSubmissionId='';
const statusLabel={pending:'審査待ち',approved:'承認',rejected:'却下',published:'掲載済み'};

function status(node,text,type=''){if(!node)return;node.textContent=text;node.classList.remove('ok','warn');if(type)node.classList.add(type)}
function formatDate(value){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function safeUrl(value){if(!value)return'';try{const u=new URL(value,location.origin);if(['https:','http:','blob:'].includes(u.protocol))return u.href}catch(_e){}return''}
async function loadConfig(){const r=await fetch(CONFIG_URL,{cache:'no-store'});if(!r.ok)throw new Error('管理設定を読み込めませんでした。');const v=await r.json();if(!v||typeof v!=='object')throw new Error('管理設定が不正です。');return v}
async function api(action,payload={}){if(!config?.enabled||!/^https:\/\//i.test(config.endpoint||''))throw new Error('審査APIが未接続です。');if(!adminCode)throw new Error('管理コードを入力してください。');const header=config.code_header||'x-bantai-admin-code';const r=await fetch(config.endpoint,{method:'POST',headers:{'content-type':'application/json',[header]:adminCode},body:JSON.stringify({action,...payload}),credentials:'omit',redirect:'follow',cache:'no-store'});let data={};try{data=await r.json()}catch(_e){}if(!r.ok||data?.ok===false)throw new Error(data?.message||`管理APIエラー（${r.status}）`);return data}
function setUnlocked(on){els.dashboard.hidden=!on;els.login.hidden=on;if(on)els.dashboard.scrollIntoView({behavior:'smooth',block:'start'})}
async function unlock(code,{silent=false}={}){adminCode=String(code||'').trim();if(!adminCode){if(!silent)status(els.loginStatus,'管理コードを入力してください。','warn');return false}els.unlock.disabled=true;if(!silent)status(els.loginStatus,'管理コードを確認しています…');try{await api('health');if(els.remember.checked)sessionStorage.setItem(SESSION_KEY,adminCode);else sessionStorage.removeItem(SESSION_KEY);status(els.loginStatus,'管理画面を開きました。','ok');setUnlocked(true);await loadQueue({openRequested:true});return true}catch(err){adminCode='';sessionStorage.removeItem(SESSION_KEY);if(!silent)status(els.loginStatus,err?.message||'管理コードを確認できませんでした。','warn');return false}finally{els.unlock.disabled=!config?.enabled}}
function lock(){if(els.dialog.open)els.dialog.close();adminCode='';submissions=[];activeSubmissionId='';sessionStorage.removeItem(SESSION_KEY);els.code.value='';els.queue.replaceChildren();setUnlocked(false);status(els.loginStatus,'管理画面を閉じました。');els.login.scrollIntoView({behavior:'smooth',block:'start'})}
async function loadQueue({openRequested=false}={}){status(els.queueStatus,'審査一覧を読み込んでいます…');els.refresh.disabled=true;try{const result=await api('list',{status:'all',limit:100});submissions=Array.isArray(result.submissions)?result.submissions:[];updateCounts();renderQueue();status(els.queueStatus,`${submissions.length}件を読み込みました。`,'ok');if(openRequested){const wanted=new URLSearchParams(location.search).get('submission');const row=submissions.find(x=>x.submission_id===wanted);if(row)openDialog(row)}}catch(err){status(els.queueStatus,err?.message||'審査一覧を読み込めませんでした。','warn')}finally{els.refresh.disabled=false}}
function updateCounts(){for(const k of Object.keys(els.counts))els.counts[k].textContent=String(submissions.filter(x=>x.status===k).length)}
function rowsForFilter(){return activeFilter==='all'?submissions:submissions.filter(x=>x.status===activeFilter)}
function firstPhoto(row){const photos=Array.isArray(row.photos)?row.photos:[];return photos.find(x=>x.role==='main')||photos[0]||null}
function renderQueue(){els.queue.replaceChildren();const rows=rowsForFilter();els.empty.hidden=rows.length!==0;for(const row of rows){const card=document.createElement('article');card.className='review-card';const thumb=document.createElement('div');thumb.className='review-thumb';const p=firstPhoto(row),src=safeUrl(p?.url||p?.image_url);if(src){const img=document.createElement('img');img.src=src;img.alt=`${row.university_name||'大学'} 投稿写真`;img.loading='lazy';thumb.append(img)}else{const none=document.createElement('div');none.className='no-photo';none.textContent='写真プレビューなし';thumb.append(none)}const main=document.createElement('div');main.className='review-main';const badge=document.createElement('span');badge.className=`status-badge ${row.status||'pending'}`;badge.textContent=statusLabel[row.status]||row.status||'審査待ち';const h=document.createElement('h3');h.textContent=row.university_name||'大学名未設定';const metaText=document.createElement('p');metaText.textContent=`${formatDate(row.submitted_at)} / ${row.submission_id||''}`;const meta=document.createElement('div');meta.className='review-meta';for(const text of [`${row.photo_count||0}枚`,row.university_id||'',row.main_photo?.original_name?`メイン: ${row.main_photo.original_name}`:'メイン指定あり']){const span=document.createElement('span');span.textContent=text;meta.append(span)}main.append(badge,h,metaText,meta);const button=document.createElement('button');button.type='button';button.className='review-open';button.textContent='写真を審査';button.addEventListener('click',()=>openDialog(row));card.append(thumb,main,button);els.queue.append(card)}}
function openDialog(row){activeSubmissionId=row.submission_id||'';els.dialogStatus.className=`status-badge ${row.status||'pending'}`;els.dialogStatus.textContent=statusLabel[row.status]||row.status||'審査待ち';els.dialogUniversity.textContent=row.university_name||'大学名未設定';els.dialogMeta.textContent=`${row.photo_count||0}枚 / ${formatDate(row.submitted_at)}`;els.dialogId.textContent=row.submission_id||'—';els.dialogCount.textContent=`${row.photo_count||0}枚`;els.dialogDate.textContent=formatDate(row.submitted_at);els.dialogUniversityId.textContent=row.university_id||'—';els.reviewerNote.value=row.reviewer_note||'';status(els.dialogActionStatus,'');els.dialogGallery.replaceChildren();const photos=Array.isArray(row.photos)?row.photos:[];photos.forEach((photo,index)=>{const box=document.createElement('figure');box.className='dialog-photo';const src=safeUrl(photo?.url||photo?.image_url);if(src){const img=document.createElement('img');img.src=src;img.alt=`${row.university_name||'大学'} 写真${index+1}`;box.append(img)}const role=document.createElement('span');role.className='photo-role';role.textContent=photo?.role==='main'?'★ メイン':`サブ ${index+1}`;box.append(role);els.dialogGallery.append(box)});if(!photos.length){const none=document.createElement('p');none.textContent='写真プレビューを取得できませんでした。審査用ZIPを確認してください。';els.dialogGallery.append(none)}els.dialogAgreements.replaceChildren();const a=row.agreements||{};for(const [label,ok] of [['撮影・権利',a.rights],['生成AI・実景保持',a.no_ai],['掲載許諾',a.license]]){const li=document.createElement('li');li.textContent=`${ok?'✓':'×'} ${label}`;els.dialogAgreements.append(li)}const packageUrl=safeUrl(row.package_url);els.download.hidden=!packageUrl;els.download.href=packageUrl||'#';els.publish.hidden=row.status!=='approved';els.markPending.hidden=row.status==='pending';if(!els.dialog.open){if(typeof els.dialog.showModal==='function')els.dialog.showModal();else els.dialog.setAttribute('open','')}}
async function updateActive(nextStatus){if(!activeSubmissionId)return;const buttons=[els.markPending,els.reject,els.approve,els.publish];buttons.forEach(b=>b.disabled=true);status(els.dialogActionStatus,'更新しています…');try{const id=activeSubmissionId;await api('update',{submission_id:id,status:nextStatus,reviewer_note:els.reviewerNote.value.trim()});await loadQueue();const row=submissions.find(x=>x.submission_id===id);if(row)openDialog(row);status(els.dialogActionStatus,`${statusLabel[nextStatus]||nextStatus}に更新しました。`,'ok')}catch(err){status(els.dialogActionStatus,err?.message||'更新に失敗しました。','warn')}finally{buttons.forEach(b=>b.disabled=false)}}

els.form.addEventListener('submit',e=>{e.preventDefault();unlock(els.code.value)});els.refresh.addEventListener('click',()=>loadQueue());els.lock.addEventListener('click',lock);els.filters.forEach(button=>button.addEventListener('click',()=>{activeFilter=button.dataset.status||'pending';els.filters.forEach(x=>x.classList.toggle('active',x===button));renderQueue()}));els.markPending.addEventListener('click',()=>updateActive('pending'));els.reject.addEventListener('click',()=>updateActive('rejected'));els.approve.addEventListener('click',()=>updateActive('approved'));els.publish.addEventListener('click',()=>updateActive('published'));

(async()=>{try{config=await loadConfig();const connected=!!(config?.enabled&&/^https:\/\//i.test(config.endpoint||''));els.backend.textContent=connected?'審査API 接続済み':'審査API 未接続';els.backend.classList.toggle('online',connected);els.backend.classList.toggle('offline',!connected);els.unlock.disabled=!connected;if(!connected){status(els.loginStatus,'審査APIの接続設定がまだ完了していません。本人写真登録は上のボタンから利用できます。','warn');return}const saved=config.session_storage?sessionStorage.getItem(SESSION_KEY):'';if(saved){els.code.value=saved;await unlock(saved,{silent:true})}}catch(err){els.backend.textContent='管理設定エラー';status(els.loginStatus,err?.message||'管理設定を確認できませんでした。','warn');els.unlock.disabled=true}})();
})();
