#!/usr/bin/env python3
"""Validate the SEO metadata generated by generate_seo_metadata.py for the
47 prefecture pages and the portal: meta description counts, canonical
tags, JSON-LD (BreadcrumbList/CollectionPage/WebSite), visual breadcrumb,
sitemap.xml coverage, and the internal related-prefecture links (adjacency
+ same-region)."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PREFECTURE_METADATA_JSON = ROOT / "data" / "school-database" / "prefecture-metadata.json"
CARD_METADATA_JSON = ROOT / "data" / "school-database" / "prefecture-card-metadata.json"
PAGE_DIR = ROOT / "tools" / "school-database"
PORTAL_PAGE = PAGE_DIR / "index.html"
SITEMAP_PATH = ROOT / "sitemap.xml"
SITE_ORIGIN = "https://bantai-education-design.github.io"

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_seo_metadata import PREFECTURE_ADJACENCY  # noqa: E402


def format_number(n: int) -> str:
    return f"{n:,}"


def test_meta_description_counts_match_current_data() -> None:
    prefecture_metadata = json.loads(PREFECTURE_METADATA_JSON.read_text(encoding="utf-8"))
    checked = 0
    for meta in prefecture_metadata:
        slug = meta["slug"]
        html = (PAGE_DIR / slug / "index.html").read_text(encoding="utf-8")
        m = re.search(r"合計\s*([\d,]+)\s*校・園", html)
        if not m:
            continue  # 東京都のようにdescriptionに件数を含まないページは対象外
        assert m.group(1) == format_number(meta["total"]), (
            f"{slug}: meta descriptionの件数が現行データと一致しません（表示={m.group(1)} / 実際={meta['total']}）"
        )
        checked += 1
    assert checked >= 40, f"検証できたページが少なすぎます（{checked}件）"


def test_portal_description_shows_current_national_total() -> None:
    prefecture_metadata = json.loads(PREFECTURE_METADATA_JSON.read_text(encoding="utf-8"))
    national_total = sum(m["total"] for m in prefecture_metadata)
    html = PORTAL_PAGE.read_text(encoding="utf-8")
    assert f"合計{format_number(national_total)}件" in html, "ポータルdescriptionの全国合計件数が現行データと一致しません"
    assert "47都道府県" in html
    assert "東京都・埼玉県対応" not in Path(ROOT / "index.html").read_text(encoding="utf-8"), (
        "ルートページに古い「東京都・埼玉県対応」表記が残っています"
    )


def test_canonical_tags_present_once_and_correct() -> None:
    card_payload = json.loads(CARD_METADATA_JSON.read_text(encoding="utf-8"))
    for pref in card_payload["prefectures"]:
        slug = pref["prefecture_code"]
        html = (PAGE_DIR / slug / "index.html").read_text(encoding="utf-8")
        expected = f'<link rel="canonical" href="{SITE_ORIGIN}{pref["url"]}">'
        count = html.count('rel="canonical"')
        assert count == 1, f"{slug}: canonicalタグの数が想定と異なります（{count}件）"
        assert expected in html, f"{slug}: canonicalタグのURLが一致しません"


def test_json_ld_valid_and_correct_for_prefectures() -> None:
    card_payload = json.loads(CARD_METADATA_JSON.read_text(encoding="utf-8"))
    for pref in card_payload["prefectures"]:
        slug = pref["prefecture_code"]
        name = pref["prefecture_name"]
        html = (PAGE_DIR / slug / "index.html").read_text(encoding="utf-8")
        m = re.search(r'<script type="application/ld\+json">\n(.*?)\n  </script>', html, re.S)
        assert m, f"{slug}: JSON-LDが見つかりません"
        data = json.loads(m.group(1))
        types = [d["@type"] for d in data]
        # FAQPageは feature/prefecture-page-seo-content で追加された3件目の
        # 要素（tools/school-database/prefecture_seo_content.pyのFAQ Q&Aと
        # 完全に対応、generate_seo_metadata.pyのadd_prefecture_json_ld()が
        # prefecture_metadataを渡された場合に常に付与する）。
        assert types == ["BreadcrumbList", "CollectionPage", "FAQPage"], (
            f"{slug}: JSON-LDの@type構成が想定と異なります: {types}"
        )

        breadcrumb = data[0]
        names = [item["name"] for item in breadcrumb["itemListElement"]]
        assert names == ["ホーム", "全国学校データベース", f"{name}学校データベース"], (
            f"{slug}: パンくずの名称が一致しません: {names}"
        )
        assert breadcrumb["itemListElement"][-1]["item"] == f"{SITE_ORIGIN}{pref['url']}"

        collection = data[1]
        assert collection["url"] == f"{SITE_ORIGIN}{pref['url']}"
        assert collection["isPartOf"]["@type"] == "WebSite"

        faq_page = data[2]
        assert len(faq_page["mainEntity"]) == 7, f"{slug}: FAQPageのQ&A件数が7件ではありません"
        for question in faq_page["mainEntity"]:
            assert question["name"], f"{slug}: FAQPageに空の質問があります"
            assert question["acceptedAnswer"]["text"], f"{slug}: FAQPageに空の回答があります"


def test_json_ld_valid_for_portal() -> None:
    html = PORTAL_PAGE.read_text(encoding="utf-8")
    m = re.search(r'<script type="application/ld\+json">\n(.*?)\n  </script>', html, re.S)
    assert m, "ポータルのJSON-LDが見つかりません"
    data = json.loads(m.group(1))
    types = [d["@type"] for d in data]
    assert types == ["WebSite", "BreadcrumbList"], f"ポータルのJSON-LD @type構成が想定と異なります: {types}"


def test_visual_breadcrumb_present_once_matches_json_ld() -> None:
    card_payload = json.loads(CARD_METADATA_JSON.read_text(encoding="utf-8"))
    for pref in card_payload["prefectures"]:
        slug = pref["prefecture_code"]
        name = pref["prefecture_name"]
        html = (PAGE_DIR / slug / "index.html").read_text(encoding="utf-8")
        assert html.count('class="pref-breadcrumb"') == 1, f"{slug}: パンくずが重複または欠落しています"
        assert f'aria-current="page">{name}学校データベース</span>' in html, f"{slug}: パンくず表示名が一致しません"


def test_sitemap_covers_all_47_and_portal_no_duplicates() -> None:
    card_payload = json.loads(CARD_METADATA_JSON.read_text(encoding="utf-8"))
    sitemap = SITEMAP_PATH.read_text(encoding="utf-8")
    locs = re.findall(r"<loc>([^<]+)</loc>", sitemap)
    assert len(locs) == len(set(locs)), "sitemap.xmlにURLの重複があります"

    expected_urls = {f"{SITE_ORIGIN}{pref['url']}" for pref in card_payload["prefectures"]}
    expected_urls.add(f"{SITE_ORIGIN}/tools/school-database/")
    missing = expected_urls - set(locs)
    assert not missing, f"sitemap.xmlに登録されていないURLがあります: {missing}"


def test_adjacency_data_is_symmetric_and_covers_all_47() -> None:
    card_payload = json.loads(CARD_METADATA_JSON.read_text(encoding="utf-8"))
    all_slugs = {p["prefecture_code"] for p in card_payload["prefectures"]}
    assert set(PREFECTURE_ADJACENCY.keys()) == all_slugs, "隣接データの都道府県セットが47件と一致しません"

    for slug, neighbors in PREFECTURE_ADJACENCY.items():
        assert slug not in neighbors, f"{slug}: 自分自身を隣接県に含めています"
        for n in neighbors:
            assert slug in PREFECTURE_ADJACENCY.get(n, []), (
                f"{slug} は {n} を隣接県としていますが、{n} 側に {slug} が含まれていません（非対称）"
            )

    # 既知の代表事実（国土数値情報N03の幾何学的検証で確認済み）との整合性チェック。
    assert len(PREFECTURE_ADJACENCY["nagano"]) == 8, "長野県の隣接県数は8のはずです"
    assert len(PREFECTURE_ADJACENCY["saitama"]) == 7, "埼玉県の隣接都県数は7のはずです"
    assert len(PREFECTURE_ADJACENCY["gifu"]) == 7, "岐阜県の隣接県数は7のはずです"
    assert len(PREFECTURE_ADJACENCY["nagasaki"]) == 1, "長崎県の陸上隣接県数は1のはずです"
    assert PREFECTURE_ADJACENCY["hokkaido"] == [], "北海道は陸続きの隣接県がないはずです"
    assert PREFECTURE_ADJACENCY["okinawa"] == [], "沖縄県は陸続きの隣接県がないはずです"

    # 佐賀県⇔熊本県は実際には県境を共有していない（N03検証で確認、benricho.org等の
    # 民間サイトの一覧を鵜呑みにした過去の誤りを修正済み）。
    assert "kumamoto" not in PREFECTURE_ADJACENCY["saga"], "佐賀県と熊本県は県境を共有していません"
    assert "saga" not in PREFECTURE_ADJACENCY["kumamoto"], "佐賀県と熊本県は県境を共有していません"

    # 山口県⇔福岡県は関門海峡で隔てられており、橋・トンネルで連結されていても
    # N03の陸地ポリゴン同士は接触していない（海を挟む県は隣接に含めないルール）。
    assert "fukuoka" not in PREFECTURE_ADJACENCY["yamaguchi"], "山口県と福岡県は関門海峡を挟み陸上隣接しません"
    assert "yamaguchi" not in PREFECTURE_ADJACENCY["fukuoka"], "山口県と福岡県は関門海峡を挟み陸上隣接しません"

    # 広島県⇔鳥取県は実在する陸上県境（約22km）を持つ（旧データで欠落していた）。
    assert "tottori" in PREFECTURE_ADJACENCY["hiroshima"], "広島県と鳥取県は陸上隣接するはずです"
    assert "hiroshima" in PREFECTURE_ADJACENCY["tottori"], "広島県と鳥取県は陸上隣接するはずです"

    # 瀬戸内海を挟む本州四国連絡橋沿いの2ペアは、N03上でポリゴンが技術的に
    # ごく短く接触するが（離島同士の偶発的接触、クラスタ分析で最大でも3.2km
    # ＝実在国境の最小値4.19kmに満たない）、海を挟む県として隣接に含めない。
    assert "ehime" not in PREFECTURE_ADJACENCY["hiroshima"], "広島県と愛媛県は瀬戸内海を挟み陸上隣接しません"
    assert "kagawa" not in PREFECTURE_ADJACENCY["okayama"], "岡山県と香川県は瀬戸内海を挟み陸上隣接しません"


def test_adjacency_matches_geospatial_ground_truth() -> None:
    """PREFECTURE_ADJACENCY must exactly match the N03-derived ground truth
    computed by tools/school-database/compute_prefecture_adjacency.py (dissolve
    each prefecture's municipality polygons, intersect boundaries pairwise,
    cluster-filter out sea-strait islet contacts). Regenerate
    prefecture_adjacency_ground_truth.json by re-running that script (and
    compute_adjacency_clusters.py) against data-source/n03-2026/ if this ever
    needs to change."""
    ground_truth_path = PAGE_DIR / "prefecture_adjacency_ground_truth.json"
    if not ground_truth_path.exists():
        return  # raw N03 source not present in this checkout; skip silently
    ground_truth = json.loads(ground_truth_path.read_text(encoding="utf-8"))
    for slug in ground_truth:
        assert sorted(PREFECTURE_ADJACENCY.get(slug, [])) == sorted(ground_truth[slug]), (
            f"{slug}: PREFECTURE_ADJACENCY が幾何学的検証結果と一致しません "
            f"(現在={sorted(PREFECTURE_ADJACENCY.get(slug, []))}, "
            f"正解={sorted(ground_truth[slug])})"
        )


def test_related_links_match_adjacency_and_region_data() -> None:
    card_payload = json.loads(CARD_METADATA_JSON.read_text(encoding="utf-8"))
    name_by_slug = {p["prefecture_code"]: p["prefecture_name"] for p in card_payload["prefectures"]}
    region_by_slug = {p["prefecture_code"]: p["region"]["code"] for p in card_payload["prefectures"]}
    slugs_by_region: dict[str, list[str]] = {}
    for p in card_payload["prefectures"]:
        slugs_by_region.setdefault(p["region"]["code"], []).append(p["prefecture_code"])

    for pref in card_payload["prefectures"]:
        slug = pref["prefecture_code"]
        html = (PAGE_DIR / slug / "index.html").read_text(encoding="utf-8")
        block_match = re.search(r"<!-- pref-related-links:start -->(.*?)<!-- pref-related-links:end -->", html, re.S)
        assert block_match, f"{slug}: 関連都道府県リンクのマーカーが見つかりません"
        block = block_match.group(1)

        expected_adjacent = [s for s in PREFECTURE_ADJACENCY.get(slug, []) if s in name_by_slug]
        expected_same_region = [
            s for s in slugs_by_region.get(region_by_slug[slug], [])
            if s != slug and s not in expected_adjacent
        ]

        for s in expected_adjacent + expected_same_region:
            expected_link = f'href="/tools/school-database/{s}/">{name_by_slug[s]}</a>'
            assert expected_link in block, f"{slug}: 関連リンクに{name_by_slug[s]}への正しいリンクがありません"

        if not expected_adjacent and not expected_same_region:
            assert block.strip() == "", f"{slug}: 隣接・同地方が0件のはずなのにセクションが出力されています"


if __name__ == "__main__":
    test_meta_description_counts_match_current_data()
    test_portal_description_shows_current_national_total()
    test_canonical_tags_present_once_and_correct()
    test_json_ld_valid_and_correct_for_prefectures()
    test_json_ld_valid_for_portal()
    test_visual_breadcrumb_present_once_matches_json_ld()
    test_sitemap_covers_all_47_and_portal_no_duplicates()
    test_adjacency_data_is_symmetric_and_covers_all_47()
    test_related_links_match_adjacency_and_region_data()
    print("SEO metadata validation passed successfully.")
