#!/usr/bin/env python3
"""Validate the 校種×設置区分 matrix-style "収録範囲" tables generated by
regenerate_matrix_tables.py for 東京都 and 埼玉県 — the two prefectures
whose individual page shows a column per establishment type rather than the
single-件数-column table used by the other 45 (verified separately by
test_prefecture_page_enrichment.py).

Every cell, row total, and grand total must be independently recomputable
from data/school-database/{slug}.json. 埼玉県's table previously grouped
several school types together ("中学校・義務教育学校" etc.); this also
confirms that grouping no longer exists."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHOOL_DB_DIR = ROOT / "data" / "school-database"
PAGE_DIR = ROOT / "tools" / "school-database"

SCHOOL_TYPE_ORDER = [
    "幼稚園", "幼保連携型認定こども園", "小学校", "中学校",
    "義務教育学校", "高等学校", "中等教育学校", "特別支援学校",
]
MATRIX_SLUGS = ["tokyo", "saitama"]


def format_number(n: int) -> str:
    return f"{n:,}"


def _check_matrix_for_slug(slug: str) -> None:
    records = json.loads((SCHOOL_DB_DIR / f"{slug}.json").read_text(encoding="utf-8"))
    html = (PAGE_DIR / slug / "index.html").read_text(encoding="utf-8")

    header_match = re.search(r"本データベースの収録範囲[（(]\s*合計\s*([\d,]+)\s*校・園[）)]", html)
    assert header_match, f"{slug}: 収録範囲の見出しが見つかりません"
    assert header_match.group(1) == format_number(len(records)), (
        f"{slug}: 収録範囲見出しがJSON件数と一致しません（表示={header_match.group(1)} / 実件数={len(records)}）"
    )

    cross: dict[str, dict[str, int]] = {}
    for r in records:
        cross.setdefault(r["school_type"], {})
        cross[r["school_type"]][r["establishment_type"]] = cross[r["school_type"]].get(r["establishment_type"], 0) + 1

    est_present = [e for e in ["国立", "公立", "私立", "その他"] if any(e in ests for ests in cross.values())]
    assert est_present == ["公立", "私立"], f"{slug}: 現行データの設置区分が想定と異なります: {est_present}"

    marker_start = f"<!-- {slug}-matrix-table:start -->"
    marker_end = f"<!-- {slug}-matrix-table:end -->"
    matrix_match = re.search(re.escape(marker_start) + r"(.*?)" + re.escape(marker_end), html, re.S)
    assert matrix_match, f"{slug}: マトリクステーブルが見つかりません"
    matrix_html = matrix_match.group(1)

    # 校種の grouping（旧「中学校・義務教育学校」等）が残っていないこと。
    assert "・義務教育学校" not in matrix_html, f"{slug}: 校種のグルーピングが残っています"
    assert "・中等教育学校" not in matrix_html, f"{slug}: 校種のグルーピングが残っています"

    grand_total = 0
    for t in SCHOOL_TYPE_ORDER:
        if t not in cross:
            continue
        row_total = sum(cross[t].values())
        grand_total += row_total
        unit = "園" if t in ("幼稚園", "幼保連携型認定こども園") else "校"
        for est in est_present:
            count = cross[t].get(est, 0)
            if count > 0:
                expected_cell = f"✓ ({format_number(count)}{unit})"
                assert expected_cell in matrix_html, (
                    f"{slug}/{t}/{est}: マトリクスのセル表示が一致しません（期待値含む文字列: {expected_cell}）"
                )
            else:
                expected_zero = f"0{unit}"
                row_pattern = re.search(re.escape(t) + r"</td>(.*?)</tr>", matrix_html, re.S)
                assert row_pattern and expected_zero in row_pattern.group(1), (
                    f"{slug}/{t}/{est}: 0件セルの表示が見つかりません（期待値: {expected_zero}）"
                )

    assert grand_total == len(records), (
        f"{slug}: マトリクス全行合計がJSON件数と一致しません（マトリクス={grand_total} / JSON={len(records)}）"
    )


def test_tokyo_matrix_matches_current_data() -> None:
    _check_matrix_for_slug("tokyo")


def test_saitama_matrix_matches_current_data() -> None:
    _check_matrix_for_slug("saitama")


if __name__ == "__main__":
    for slug in MATRIX_SLUGS:
        _check_matrix_for_slug(slug)
    print("Matrix table validation (tokyo, saitama) passed successfully.")
